repos:
-   repo: local
    hooks:
    -   id: bump-version
        name: Bump-Version
        description: Inject branch version into documentation
        entry: hooks/bump-version
        language: script