# Configuration for 4004-cli.

title = "Configuration"

[asm]
input = "fred"
output = "fred"
type = ["BIN", "H"]
exec = true
monitor = true
quiet = false

[dis]
objectfile = "default.obj"
inst = 3
labels = false

[exe]
objectfile = "default.obj"
quiet = false

[results]
show = ['REGS']